task_list/task_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls'))
]

task_list/tasks/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskDetailView,
    OwnerListView,
    OwnerDetailView,
    index,
    SubTaskDetailView,
    PersonDetailView,
)

app_name = 'tasks'
urlpatterns = [
    path('', index, name='index'),
    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/<int:pk>', TaskDetailView.as_view(), name='task-detail'),
    path('owners/', OwnerListView.as_view(), name='person-list'),
    path('owners/<int:pk>', PersonDetailView.as_view(), name='person-detail'),
    path('subtasks/<int:pk>', SubTaskDetailView.as_view(), name='subtask-detail')
]

task_list/task/models.py
from django.db import models

# Create your models here.

task_list/tasks/models.py
from django.db import models
from django.urls import reverse
import datetime as dt


# Create your models here.
class AbstractTask(models.Model):
    title = models.CharField(max_length=150, help_text='Task Name')
    owner = models.ForeignKey('Owner', null=False, blank=False, on_delete=models.CASCADE)

    description = models.TextField(blank=True, null=True)

    duration_days = models.IntegerField(default=0, null=True, blank=True)
    duration_hours = models.IntegerField(default=0, null=True, blank=True)
    duration_minutes = models.IntegerField(default=0, null=True, blank=True)

    due_date = models.DateTimeField(blank=False, null=False)

    started = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)

    @property
    def start_by(self):
        seconds = float((self.duration_hours*3600) + (self.duration_minutes * 60))
        return self.due_date - dt.timedelta(
            days=float(self.duration_days), seconds=seconds
        )

    @property
    def overdue(self):
        return self.due_date < dt.datetime.now(dt.timezone.utc)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['due_date']
        abstract = True


class Task(AbstractTask):
    stakeholders = models.ManyToManyField('Stakeholder', blank=True)

    def get_absolute_url(self):
        return reverse('tasks:task-detail', kwargs={'pk': self.pk})


class Person(models.Model):
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)
    department = models.ForeignKey('Department', null=True, blank=False, on_delete=models.SET_NULL)

    def name(self):
        return f'{self.first} {self.last}'

    def __str__(self):
        return self.name()

    def get_absolute_url(self):
        return reverse('tasks:person-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        Owner.objects.create(person=self)
        Stakeholder.objects.create(person=self)


class Owner(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def name(self):
        return f'{self.person.first} {self.person.last}'

    def __str__(self):
        return self.name()

    def get_absolute_url(self):
        return reverse('tasks:owner-detail', kwargs={'pk': self.pk})


class Department(models.Model):
    name = models.CharField(max_length=100, help_text='Team or Department')

    def __str__(self):
        return self.name


class Stakeholder(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def name(self):
        return f'{self.person.first} {self.person.last}'

    def __str__(self):
        return self.name()


class SubTask(AbstractTask):
    owner = models.ForeignKey(Owner, null=True, blank=True, on_delete=models.SET_NULL)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    work_time = models.DecimalField(default=0, decimal_places=5, max_digits=300)

    def get_absolute_url(self):
        return reverse('tasks:subtask-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.started:
            if not self.task.started:
                self.task.started = True
                self.task.save()
        super().save(*args, **kwargs)

    def start(self):
        self.start_time = dt.datetime.now()
        self.timing = True

    def end(self):

        if self.timing:
            self.end_time = dt.datetime.now()
            self.work_time += (self.end_time - self.start_time).seconds
            self.timing = False

task_list/task/views.py
from django.shortcuts import render

# Create your views here.

task_list/tasks/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Task, Department, Owner, Stakeholder, Person, SubTask


# Create your views here.
class TaskListView(ListView):
    model = Task


class TaskDetailView(DetailView):
    model = Task


class OwnerDetailView(DetailView):
    model = Person


class OwnerListView(ListView):
    model = Person

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)


def index(request):
    return render(request, 'tasks/index.html')


class SubTaskDetailView(DetailView):
    model = SubTask


class PersonDetailView(DetailView):
    model = Person

task_list/tasks/templates/tasks/index.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the Task Site</h1>

{% endblock %}

task_list/tasks/templates/tasks/owner_list.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the Owner List</h1>

<ul>
    {% for owner in owner_list %}
    <li><a href="{{ owner.get_absolute_url }}">{{ owner.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

task_list/tasks/templates/tasks/person_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Person Name: {{ person.name }}</h1>
<hr>
<h3>Tasks</h3>
<ul>
{% for owner in person.owner_set.all %}
    {% for task in owner.task_set.all %}
    <li><a href="{{ task.get_absolute_url }}">{{ task.title }}</a> - {{ task.due_date }}</li>
    {% endfor %}
{% endfor %}
</ul>
<hr>
<h3>Task Stakeholder</h3>
{% for stakeholder in person.stakeholder_set.all %}
    {% for task in stakeholder.task_set.all %}
    <li><a href="{{ task.get_absolute_url }}">{{ task.title }}</a> - {{ task.due_date }}</li>
    {% endfor %}
{% endfor %}
{% endblock %}

task_list/tasks/templates/tasks/person_list.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the Task Users List</h1>

<ul>
    {% for person in person_list %}
    <li><a href="{{ person.get_absolute_url }}">{{ person.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

task_list/tasks/templates/tasks/subtask_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Task Name: {{ subtask.title }}</h1>
<h3>{{ subtask.owner }}</h3>
<p>This task is due by {{ subtask.due_date }} and should be started by {{ subtask.start_by }}</p>
<h3>Description</h3>
<p>{{ subtask.description }}</p>
<hr>
<h5>Task Status</h5>
{% if subtask.started %}<p class="text-success">Task Started</p>
{% else %}<p class="text-danger">Task Not Started</p>{% endif %}
{% if subtask.finished %}<p class="text-success">Task Completed</p>
{% else %}<p class="text-danger">Task Incomplete</p>{% endif %}
{% endblock %}

task_list/tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Task Name: {{ task.title }}</h1>
<h3>{{ task.owner }}</h3>
<h5>
{% for stakeholder in task.stakeholders_set.all %}
{{ stakeholder }},
    {% endfor %}</h5>
<p>This task is due by {{ task.due_date }} and should be started by {{ task.start_by }}</p>
<h3>Description</h3>
<p>{{ task.description }}</p>
<hr>
<h5>Task Status</h5>
{% if task.started %}<span class="text-success">Task Started</span>
{% else %}<span class="text-danger">Task Not Started</span>{% endif %} -
{% if task.finished %}<span class="text-success">Task Completed</span>
{% else %}<span class="text-danger">Task Incomplete</span>{% endif %}
<hr>
<h5>Sub Task Status</h5>
<ul>
{% for sub_task in task.subtask_set.all %}
    <li><a href="{{ sub_task.get_absolute_url }}">{{ sub_task.title }}</a> - due {{ sub_task.due_date }}<br>
        {% if sub_task.started %} <p class="text-success">Task Started
        {% if sub_task.finished %} - Task Completed</p>
        {% else %}<span class="text-danger"> - Task Incomplete</span></p>
        {% endif %}
        {% else %}<p class="text-danger">Task Not Started</p>
        {% endif %}
    </li>
{% endfor %}
</ul>
{% endblock %}

task_list/tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{% block content %}
<h1>This is the Task List</h1>

<ul>
    {% for task in task_list %}
    <li><a href="{{ task.get_absolute_url }}">{{ task.title }}</a> - <a href="{{ task.owner.person.get_absolute_url }}">({{ task.owner }})</a> - due by: {{ task.due_date }}</li>
    {% endfor %}
</ul>

{% endblock %}

task_list/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="UTF-8">
    <title>Task List</title>
    {% endblock %}
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
{% block sidebar %}
<nav class="sidebar-nav">
    <ul>
        <li><a href="{% url 'tasks:index' %}">Home</a></li>
        <li><a href="{% url 'tasks:task-list' %}">Tasks</a></li>
        <li><a href="{% url 'tasks:person-list' %}">Owners</a></li>
    </ul>
</nav>

{% endblock %}
</div>
        <div class="col-sm-10">
{% block content %}
{% endblock %}
        </div>
    </div>
</div>
</body>
</html>